#include <Arduino.h>
#include <ArduinoJson.h>
#include <Adafruit_INA219.h>
#include <DHT.h>
#include <ESP32Servo.h>
#include <Wire.h>
#include "hardware_profile.h"
#include "safety_state.h"

namespace {
constexpr char FIRMWARE_VERSION[] = "3.0.0";
constexpr char PROTOCOL_VERSION[] = "3.0";
constexpr uint16_t ADC_SAMPLES = 32;
ahea::SafetyMachine safety(ahea::profile::OPERATION_TIMEOUT_MS, ahea::profile::MAX_SESSION_OPERATIONS);
DHT dht(ahea::profile::DHT11_PIN, DHT11);
Adafruit_INA219 ina(ahea::profile::INA219_I2C_ADDRESS);
Servo servo;
bool ina_ready = false;
String buffer, previous_id, previous_response;

template <typename T> void measurement(JsonArray list, const char* name, T value, const char* unit, const String& device, bool valid = true) {
  JsonObject item = list.add<JsonObject>(); item["channel"] = name; item["value"] = value; item["unit"] = unit; item["deviceId"] = device; item["quality"] = valid ? "valid" : "invalid";
}
void health(JsonArray list, const String& device, bool ok, const char* detail = nullptr) { JsonObject item = list.add<JsonObject>(); item["deviceId"] = device; item["healthy"] = ok; item["errorRate"] = ok ? 0 : 1; if (detail) item["detail"] = detail; }
JsonDocument response(const String& id, bool accepted = true, uint32_t elapsed = 0) {
  JsonDocument out; out["id"] = id; out["ok"] = true; out["error"] = nullptr; JsonObject data = out["data"].to<JsonObject>(); data["deviceUptimeMs"] = millis(); data["elapsedMs"] = elapsed; data["measurements"].to<JsonArray>(); data["series"].to<JsonArray>(); data["sensorHealth"].to<JsonArray>(); JsonObject op = data["operation"].to<JsonObject>(); op["accepted"] = accepted; op["aborted"] = false; op["timedOut"] = safety.timedOut(); op["estopLatched"] = safety.estopLatched(); op["reasons"].to<JsonArray>(); return out;
}
void send(JsonDocument& out) { String text; serializeJson(out, text); Serial.println(text); previous_id = out["id"].as<String>(); previous_response = text; }
void error(const String& id, const char* code, const char* message) { JsonDocument out; out["id"] = id; out["ok"] = false; out["data"] = nullptr; JsonObject issue = out["error"].to<JsonObject>(); issue["code"] = code; issue["message"] = message; send(out); }
bool present(uint8_t address) { Wire.beginTransmission(address); return Wire.endTransmission() == 0; }
bool begin(const String& id, ahea::OperationClass type = ahea::OperationClass::Read, bool enabled = true) { if (safety.start(type, millis(), enabled) != ahea::StartResult::Accepted) { error(id, "SAFETY_REJECTED", "Session is unarmed, busy, timed out, estopped, or this operation is disabled."); return false; } return true; }
void hello(const String& id) { JsonDocument out = response(id, true, 1); JsonArray m = out["data"]["measurements"].as<JsonArray>(); measurement(m,"firmware_version",FIRMWARE_VERSION,"semver","firmware"); measurement(m,"protocol_version",PROTOCOL_VERSION,"semver","firmware"); measurement(m,"board_identity",ahea::profile::BOARD_IDENTITY,"id","firmware"); measurement(m,"profile_id",ahea::profile::PROFILE_ID,"id","firmware"); measurement(m,"physical_enabled",ahea::profile::PHYSICAL_ENABLED,"boolean","firmware"); measurement(m,"servo_actuation_enabled",ahea::profile::SERVO_ACTUATION_ENABLED,"boolean","firmware"); health(out["data"]["sensorHealth"].as<JsonArray>(),"firmware",true); send(out); }
void scan(const String& id) { const bool mpu = present(ahea::profile::MPU6050_ADDRESS), current = present(ahea::profile::INA219_I2C_ADDRESS); JsonDocument out = response(id); JsonArray m = out["data"]["measurements"].as<JsonArray>(); measurement(m,"mpu6050_present",mpu,"boolean","mpu6050"); measurement(m,"ina219_present",current,"boolean","ina219"); health(out["data"]["sensorHealth"].as<JsonArray>(),"mpu6050",mpu); health(out["data"]["sensorHealth"].as<JsonArray>(),"ina219",current); send(out); }
void sampleDht(const String& id, const String& device) { if (!begin(id)) return; const uint32_t started = millis(); const float h = dht.readHumidity(), t = dht.readTemperature(); const bool ok = isfinite(h) && isfinite(t); safety.finish(); JsonDocument out = response(id, ok, millis() - started); JsonArray m = out["data"]["measurements"].as<JsonArray>(); measurement(m,"temperature_c",t,"C",device,ok); measurement(m,"humidity_percent",h,"%",device,ok); health(out["data"]["sensorHealth"].as<JsonArray>(),device,ok,ok ? nullptr : "DHT11 read failed: check 1 kOhm pull-up, decoupling, and wiring."); send(out); }
bool mpuRead(float& ax, float& ay, float& az, float& gx, float& gy, float& gz) { Wire.beginTransmission(ahea::profile::MPU6050_ADDRESS); Wire.write(0x3B); if (Wire.endTransmission(false) || Wire.requestFrom(ahea::profile::MPU6050_ADDRESS, static_cast<uint8_t>(14)) != 14) return false; auto read16=[](){ return static_cast<int16_t>((Wire.read()<<8)|Wire.read()); }; ax=read16()/16384.F; ay=read16()/16384.F; az=read16()/16384.F; read16(); gx=read16()/131.F; gy=read16()/131.F; gz=read16()/131.F; return true; }
void sampleMpu(const String& id, const String& device) { if (!begin(id)) return; const uint32_t started=millis(); float ax=0,ay=0,az=0,gx=0,gy=0,gz=0; const bool ok=mpuRead(ax,ay,az,gx,gy,gz); safety.finish(); JsonDocument out=response(id,ok,millis()-started); JsonArray m=out["data"]["measurements"].as<JsonArray>(); measurement(m,"accel_x_g",ax,"g",device,ok); measurement(m,"accel_y_g",ay,"g",device,ok); measurement(m,"accel_z_g",az,"g",device,ok); measurement(m,"acceleration_magnitude_g",sqrtf(ax*ax+ay*ay+az*az),"g",device,ok); measurement(m,"gyro_x_dps",gx,"deg/s",device,ok); measurement(m,"gyro_y_dps",gy,"deg/s",device,ok); measurement(m,"gyro_z_dps",gz,"deg/s",device,ok); health(out["data"]["sensorHealth"].as<JsonArray>(),device,ok); send(out); }
void voltage(const String& id, const String& device) { if (ahea::profile::VOLTAGE_ADC_PIN < 0 || ahea::profile::VOLTAGE_DIVIDER_R1_OHMS <= 0 || ahea::profile::VOLTAGE_DIVIDER_R2_OHMS <= 0) return error(id,"PROFILE_INCOMPLETE","Declare voltage ADC pin and both divider resistors before using this command."); if (!begin(id)) return; const uint32_t started=millis(); float sum=0,squares=0; bool ok=true; for(uint16_t n=0;n<ADC_SAMPLES;n++){ if(!safety.tick(millis())) { ok=false; break; } const float raw=analogRead(ahea::profile::VOLTAGE_ADC_PIN); sum+=raw; squares+=raw*raw; delay(5); } safety.finish(); const float mean=sum/ADC_SAMPLES, sd=sqrtf(max(0.F,squares/ADC_SAMPLES-mean*mean)), adc=mean/4095.F*ahea::profile::ADC_REFERENCE_VOLTS, input=adc*(ahea::profile::VOLTAGE_DIVIDER_R1_OHMS+ahea::profile::VOLTAGE_DIVIDER_R2_OHMS)/ahea::profile::VOLTAGE_DIVIDER_R2_OHMS; JsonDocument out=response(id,ok,millis()-started); JsonArray m=out["data"]["measurements"].as<JsonArray>(); measurement(m,"adc_mean",mean,"adc_raw",device,ok); measurement(m,"adc_stddev",sd,"adc_raw",device,ok); measurement(m,"divider_output_v",adc,"V",device,ok); measurement(m,"input_voltage_v",input,"V",device,ok); health(out["data"]["sensorHealth"].as<JsonArray>(),device,ok); send(out); }
void ultrasonic(const String& id, const String& device) { if (!ahea::profile::HC_SR04_ECHO_PROTECTION_REVIEWED) return error(id,"ECHO_PROTECTION_REQUIRED","Verify the HC-SR04 8.2 kOhm / 10 kOhm Echo divider before connecting GPIO35."); if (!begin(id,ahea::OperationClass::TimedIo)) return; const uint32_t started=millis(); digitalWrite(ahea::profile::HC_SR04_TRIGGER_PIN,LOW); delayMicroseconds(2); digitalWrite(ahea::profile::HC_SR04_TRIGGER_PIN,HIGH); delayMicroseconds(10); digitalWrite(ahea::profile::HC_SR04_TRIGGER_PIN,LOW); const unsigned long echo_us=pulseIn(ahea::profile::HC_SR04_ECHO_PIN,HIGH,30000); const bool ok=echo_us>0 && safety.tick(millis()); safety.finish(); const float distance=echo_us*0.0343F/2.0F; JsonDocument out=response(id,ok,millis()-started); JsonArray m=out["data"]["measurements"].as<JsonArray>(); measurement(m,"echo_duration_us",echo_us,"us",device,ok); measurement(m,"distance_cm",distance,"cm",device,ok); health(out["data"]["sensorHealth"].as<JsonArray>(),device,ok,ok?nullptr:"Echo timeout: check power, target geometry, trigger wiring, and protected Echo path."); send(out); }
void current(const String& id, const String& device) { if (!ina_ready) return error(id,"INA219_NOT_FOUND","INA219 did not respond: check 3.3 V, GND, SDA/SCL, and 4.7 kOhm pull-ups."); if (!begin(id)) return; const uint32_t started=millis(); const float bus=ina.getBusVoltage_V(), shunt=ina.getShuntVoltage_mV(), amps=ina.getCurrent_mA(), power=ina.getPower_mW(); const bool ok=isfinite(bus)&&isfinite(shunt)&&isfinite(amps); safety.finish(); JsonDocument out=response(id,ok,millis()-started); JsonArray m=out["data"]["measurements"].as<JsonArray>(); measurement(m,"bus_voltage_v",bus,"V",device,ok); measurement(m,"shunt_voltage_mv",shunt,"mV",device,ok); measurement(m,"current_ma",amps,"mA",device,ok); measurement(m,"power_mw",power,"mW",device,ok); health(out["data"]["sensorHealth"].as<JsonArray>(),device,ok); send(out); }
void servoTest(const String& id, const String& device) { if (!begin(id,ahea::OperationClass::BoundedOutput,ahea::profile::SERVO_ACTUATION_ENABLED)) return; const uint32_t started=millis(); servo.writeMicroseconds(ahea::profile::SERVO_MIN_US); delay(500); bool ok=safety.tick(millis()); if(ok){ servo.writeMicroseconds(ahea::profile::SERVO_MAX_US); delay(500); } servo.writeMicroseconds((ahea::profile::SERVO_MIN_US+ahea::profile::SERVO_MAX_US)/2); safety.finish(); JsonDocument out=response(id,ok,millis()-started); JsonArray m=out["data"]["measurements"].as<JsonArray>(); measurement(m,"pwm_min_us",ahea::profile::SERVO_MIN_US,"us",device,ok); measurement(m,"pwm_max_us",ahea::profile::SERVO_MAX_US,"us",device,ok); measurement(m,"command_duration_ms",millis()-started,"ms",device,ok); health(out["data"]["sensorHealth"].as<JsonArray>(),device,ok,"PWM was issued; visually confirm 300-600 ms motion. This alone does not prove servo health."); send(out); }
void command(const String& line) { JsonDocument request; if(deserializeJson(request,line)!=DeserializationError::Ok || !request["id"].is<const char*>() || !request["cmd"].is<const char*>() || !request["args"].is<JsonObject>()) return error("unknown","MALFORMED_REQUEST","Expected id, cmd, and args object."); const String id=request["id"].as<String>(); if(id==previous_id){Serial.println(previous_response);return;} JsonObject args=request["args"].as<JsonObject>(); for(JsonPair pair:args) if(String(pair.key().c_str())!="deviceId" && String(pair.key().c_str())!="planId") return error(id,"UNSAFE_ARGUMENT","Only deviceId and registered planId are accepted."); const String cmd=request["cmd"].as<String>(), device=args["deviceId"]|""; if(cmd=="hello")return hello(id); if(cmd=="abort"){safety.emergencyStop();JsonDocument out=response(id);out["data"]["operation"]["aborted"]=true;send(out);return;} if(cmd=="arm_session"){if(!safety.arm(ahea::profile::PHYSICAL_ENABLED))return error(id,"ARM_REJECTED","Physical profile is disabled, faulted, or estopped.");JsonDocument out=response(id);send(out);return;} if(!ahea::profile::PHYSICAL_ENABLED)return error(id,"PROFILE_DISABLED","Physical operations are disabled."); if(cmd=="scan_i2c")return scan(id); if(cmd=="sample_mpu6050")return sampleMpu(id,device); if(cmd=="sample_dht11")return sampleDht(id,device); if(cmd=="sample_voltage")return voltage(id,device); if(cmd=="sample_hc_sr04")return ultrasonic(id,device); if(cmd=="sample_ina219")return current(id,device); if(cmd=="exercise_servo")return servoTest(id,device); error(id,"UNKNOWN_COMMAND","Command is not supported."); }
} // namespace
void setup() { Serial.begin(115200); if constexpr(ahea::profile::PHYSICAL_ENABLED) { Wire.begin(ahea::profile::I2C_SDA_PIN,ahea::profile::I2C_SCL_PIN); dht.begin(); Wire.beginTransmission(ahea::profile::MPU6050_ADDRESS); Wire.write(0x6B); Wire.write(0); Wire.endTransmission(); ina_ready=ina.begin(); if(ahea::profile::VOLTAGE_ADC_PIN>=0)pinMode(ahea::profile::VOLTAGE_ADC_PIN,INPUT); pinMode(ahea::profile::HC_SR04_TRIGGER_PIN,OUTPUT); digitalWrite(ahea::profile::HC_SR04_TRIGGER_PIN,LOW); pinMode(ahea::profile::HC_SR04_ECHO_PIN,INPUT); if constexpr(ahea::profile::SERVO_ACTUATION_ENABLED)servo.attach(ahea::profile::SERVO_PWM_PIN,ahea::profile::SERVO_MIN_US,ahea::profile::SERVO_MAX_US); } }
void loop() { while(Serial.available()){const char c=static_cast<char>(Serial.read());if(c=='\n'){if(!buffer.isEmpty())command(buffer);buffer="";}else if(buffer.length()<1024)buffer+=c;else{buffer="";safety.fault();}} }
