[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit INA219@^1.2.3
  madhephaestus/ESP32Servo@^3.0.6

[env:native]
platform = native
test_build_src = yes
build_src_filter = +<safety_state.cpp>
build_flags = -std=gnu++17
